# -*- coding: utf-8 -*-

import sys
import os
import time


def phone_analyze(device_ids):
    if device_ids == "":
        cmd1 = "adb shell uiautomator dump -x"
        cmd2 = "adb shell cat "
    else:
        cmd1 = "adb -s " + str(device_ids) + " shell uiautomator dump -x"
        cmd2 = "adb -s " + str(device_ids) + " shell cat "

    dump_file = ""
    print(cmd1)
    resp1 = os.popen(cmd1)
    resp_lines1 = resp1.readlines()
    for resp_line in resp_lines1:
        if "to:" in resp_line:
            dump_file = str(resp_line).split("to:")[1].strip()

    if dump_file == "":
        print("Dump File Error Please Try Again!")
        return False
    time.sleep(3)
    cmd2 = cmd2 + dump_file
    print(cmd2)
    resp = os.popen(cmd2)
    resp_lines = resp.readlines()
    value_dict_list = []
    for resp_line in resp_lines:
        if "xml" in resp_line:
            nodes = str(resp_line).split("><")
            for node in nodes:
                temp_dict = {}
                contents = str(node).split('" ')
                for content in contents:
                    if "=" in content:
                        title = str(content).split("=")[0]
                        value = str(content).split("=")[1].replace('"', '')
                        temp_dict[title] = value
                try:
                    if len(temp_dict) > 0 and temp_dict["resource-id"] != "":
                        value_dict_list.append(temp_dict)
                except Exception as errs:
                    print("Exception ", errs)

    for value_dict in value_dict_list:
        print(value_dict)


try:
    device_id = str(sys.argv[1])
except Exception as err:
    print("Device ID is auto matching.. Exception: ", err)
    device_id = ""
phone_analyze("R3CN30CWV2H")

'''
(base) tvswtdd@M1pro Algorithm % /Users/tvswtdd/opt/anaconda3/bin/python /Users/tvswtdd/PycharmProjects/Algorithm/thinq_phone_analyze.py
Device ID is auto matching.. Exception:  list index out of range
adb -s R3CN30CWV2H shell uiautomator dump -x
adb -s R3CN30CWV2H shell cat /sdcard/window_dump.xml
Exception  'resource-id'
Exception  'resource-id'
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/action_bar_root', 'class': 'android.widget.LinearLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,0][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'android:id/content', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,0][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/slim_status_bar_player_container', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,0][1080,2192]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/navigation_bar_divider_frame', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/global_slim_status_bar_container', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/accessibility_layer_container', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/mdx_fragment_container', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/next_gen_watch_container_layout', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/scrim_view', 'class': 'android.view.View', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/next_gen_watch_layout', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/watch_player', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '동영상 플레이어', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_fragment_container', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_view', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_overlays', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '소형 플레이어 펼치기', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_overlays_custom_views_container', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/watch_while_time_bar_view_overlay', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/scrim_overlay', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '2', 'text': '', 'resource-id': 'com.google.android.youtube:id/controls_layout', 'class': 'android.widget.RelativeLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,681]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_collapse_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '최소화', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[11,79][146,214]'}
{'node index': '2', 'text': '', 'resource-id': 'com.google.android.youtube:id/autonav_toggle', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[546,79][681,214]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/autonav_toggle_button', 'class': 'android.widget.Switch', 'package': 'com.google.android.youtube', 'content-desc': '자동재생 사용 안함', 'checkable': 'true', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[557,79][669,214]'}
{'node index': '3', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_additional_view_container', 'class': 'android.widget.LinearLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[681,79][973,214]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/media_route_button', 'class': 'android.view.View', 'package': 'com.google.android.youtube', 'content-desc': '전송 버튼입니다. 기기가 연결 해제되었습니다', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[692,79][827,214]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_subtitle_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '자막', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[838,79][973,214]'}
{'node index': '4', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_overflow_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '옵션 더보기', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[973,79][1080,214]'}
{'node index': '5', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_control_previous_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '이전 동영상', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'false', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[157,309][292,444]'}
{'node index': '6', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_control_play_pause_replay_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '동영상 재생', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[461,298][619,456]'}
{'node index': '7', 'text': '', 'resource-id': 'com.google.android.youtube:id/player_control_next_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '다음 동영상', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[788,309][923,444]'}
{'node index': '8', 'text': '', 'resource-id': 'com.google.android.youtube:id/youtube_controls_bottom_ui_container', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,444][1080,681]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/timestamps_container', 'class': 'android.widget.LinearLayout', 'package': 'com.google.android.youtube', 'content-desc': '2분 35초/1시간 12분 31초 경과', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,546][263,681]'}
{'node index': '0', 'text': '2:35', 'resource-id': 'com.google.android.youtube:id/time_bar_current_time', 'class': 'android.widget.TextView', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[45,589][103,630]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/time_bar_total_time', 'class': 'android.widget.TextView', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[103,589][229,630]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/fullscreen_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '전체화면으로 전환', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[911,512][1080,681]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/fast_forward_rewind_triangles', 'class': 'android.widget.LinearLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[212,354][327,399]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/watch_while_time_bar_view', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,729]'}
{'node index': '2', 'text': '', 'resource-id': 'com.google.android.youtube:id/engagement_panel_wrapper', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,73][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/engagement_panel', 'class': 'android.widget.RelativeLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,681][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/header_container', 'class': 'android.widget.LinearLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,681][1080,854]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/arrow_drag_handle', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '드래그 핸들', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[483,681][596,715]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/panel_header_wrapper', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,715][1080,854]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/panel_header', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,715][945,850]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/title_container', 'class': 'android.widget.LinearLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[45,752][135,813]'}
{'node index': '0', 'text': '설명', 'resource-id': 'com.google.android.youtube:id/title', 'class': 'android.widget.TextView', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[45,752][135,813]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/close_button', 'class': 'android.widget.ImageView', 'package': 'com.google.android.youtube', 'content-desc': '닫기', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[945,715][1080,851]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/panel_header_bottom_border', 'class': 'android.view.View', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,851][1080,854]'}
{'node index': '1', 'text': '', 'resource-id': 'com.google.android.youtube:id/panel_content', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,854][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/content', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,854][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/results', 'class': 'android.support.v7.widget.RecyclerView', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'true', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,854][1080,2192]'}
{'node index': '3', 'text': '', 'resource-id': 'com.google.android.youtube:id/video_metadata_layout', 'class': 'android.widget.FrameLayout', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,681][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/watch_panel', 'class': 'android.view.ViewGroup', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,681][1080,2192]'}
{'node index': '0', 'text': '', 'resource-id': 'com.google.android.youtube:id/scrim', 'class': 'android.view.View', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,681][1080,2192]'}
{'node index': '1', 'text': '', 'resource-id': 'android:id/navigationBarBackground', 'class': 'android.view.View', 'package': 'com.google.android.youtube', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'false', 'enabled': 'true', 'focusable': 'false', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'bounds': '[0,0][0,0]'}
(base) tvswtdd@M1pro Algorithm % 
'''